pub struct LogoColorEntry {
    pub names: &'static [&'static str],
    pub colors: &'static [&'static str],
    pub color_keys: Option<&'static str>,
    pub color_title: Option<&'static str>,
}

pub static LOGO_COLOR_ENTRIES: &[LogoColorEntry] = &[
    LogoColorEntry {
        names: &["adélie", "adelie"],
        colors: &["34", "37", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["aeros"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["aeon"],
        colors: &["38;5;36", "38;5;36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["aerynos"],
        colors: &["39", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["afterglow"],
        colors: &["35", "31", "33", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["aix"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["almalinux"],
        colors: &["31", "93", "34", "92", "36"],
        color_keys: Some("33"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["alpine"],
        colors: &["34"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["alpine2"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["alpine_small"],
        colors: &["34", "37"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["alpine2_small"],
        colors: &["34", "37"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["alpine3_small"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["alter"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["altlinux"],
        colors: &["33", "30", "37"],
        color_keys: Some("33"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["amazon"],
        colors: &["33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["amazon linux", "amzn"],
        colors: &["37", "38;5;178"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["amogos"],
        colors: &["37", "36"],
        color_keys: Some("39"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["anarchy"],
        colors: &["37", "34"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["android"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["android_small"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["anduinos"],
        colors: &["36", "34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["antergos"],
        colors: &["34", "36"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["antix"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["anushos"],
        colors: &["37", "30", "33", "36", "31"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["aosc os/retro", "aoscosretro"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["aosc os/retro_small", "aoscosretro_small"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["aosc os", "aoscos"],
        colors: &["34", "30", "31", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["aosc os_old", "aoscos_old"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["aperture"],
        colors: &["36", "36", "36", "36", "36", "36", "36", "36"],
        color_keys: Some("36"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["apple"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["apple_small"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["apricity"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["archbox"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["archcraft"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["archcraft2"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["arch", "archmerge"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["arch2"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["arch3"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["arch_small"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["arch_old"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["archlabs"],
        colors: &["36", "31"],
        color_keys: Some("36"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["archstrike"],
        colors: &["36", "30"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["arkane", "arkane linux"],
        colors: &["38;5;237", "38;5;130", "37"],
        color_keys: Some("38;5;130"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["armbian"],
        colors: &["37", "31"],
        color_keys: Some("39"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["armbian2"],
        colors: &["31"],
        color_keys: Some("39"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["artix", "artixlinux", "artix-linux"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["artix_small", "artixlinux_small"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["artix2_small", "artixlinux2_small"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["arco", "arcolinux", "arco-linux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["arco_small", "arcolinux_small", "arco-linux_small"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["arse", "arselinux", "arse-linux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["arya"],
        colors: &["32", "31"],
        color_keys: Some("32"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["asahi", "asahi-linux"],
        colors: &["33", "32", "31", "90", "37", "36", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["asahi2", "asahi-linux2"],
        colors: &["93", "36", "31", "91", "37", "30", "96"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["aster"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["asteroidos"],
        colors: &["38;5;160", "38;5;208", "38;5;202", "38;5;214"],
        color_keys: Some("38;5;160"),
        color_title: Some("38;5;208"),
    },
    LogoColorEntry {
        names: &["astos"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["astra", "astra linux", "astralinux"],
        colors: &["91", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ataraxia linux", "ataraxia"],
        colors: &["34", "35"],
        color_keys: Some("34"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["athenaos"],
        colors: &["34", "94"],
        color_keys: Some("34"),
        color_title: Some("94"),
    },
    LogoColorEntry {
        names: &["athenaos_old"],
        colors: &["37", "33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["aurora"],
        colors: &["34", "35", "31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["axos"],
        colors: &["38;2;222;6;255", "38;2;222;6;255"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["azos"],
        colors: &["36", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["bedrock"],
        colors: &["90", "39"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["bedrock_small"],
        colors: &["90", "39"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["biglinux"],
        colors: &["36", "33", "34"],
        color_keys: Some("33"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["bitrig"],
        colors: &["32"],
        color_keys: Some("39"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["blackarch"],
        colors: &["31", "91", "30"],
        color_keys: Some("91"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["blackmesa", "black-mesa"],
        colors: &["30"],
        color_keys: Some("30"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["blackpanther"],
        colors: &["31", "33", "94"],
        color_keys: Some("31"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["blag"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["blankon"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["bluelight"],
        colors: &["37", "34"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["bodhi"],
        colors: &["37", "93", "32"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["bonsai"],
        colors: &["36", "32", "33"],
        color_keys: Some("36"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["bredos"],
        colors: &["38;2;198;151;66"],
        color_keys: Some("38;2;198;151;66"),
        color_title: Some("38;2;198;151;66"),
    },
    LogoColorEntry {
        names: &["bsd"],
        colors: &["31", "37", "34", "33", "36"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["bunsenlabs"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["cachyos"],
        colors: &["36", "32", "30"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["cachyos_small"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["calculate"],
        colors: &["37", "33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["calinix", "calinixos"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["calinix_small", "calinixos_small"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["carbs"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["cbl-mariner"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["cel", "celos", "cel-linux", "celos-linux"],
        colors: &["35", "30"],
        color_keys: Some("36"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["center"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["centos"],
        colors: &["33", "32", "34", "35", "37"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["centos_small"],
        colors: &["33", "32", "34", "35"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["cereus", "cereus linux"],
        colors: &["38;5;173", "38;5;108", "38;5;71", "38;5;151", "38;5;72"],
        color_keys: Some("38;5;108"),
        color_title: Some("1;37"),
    },
    LogoColorEntry {
        names: &["chakra"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["chaletos"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["chapeau"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["chimera"],
        colors: &["31", "35", "34", "31"],
        color_keys: Some("35"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["chonkysealos"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["chrom", "chromeos"],
        colors: &["32", "31", "33", "34", "37"],
        color_keys: Some("32"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["cleanjaro"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["cleanjaro_small"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["clear linux", "clearlinux", "clear linux os"],
        colors: &["34", "33"],
        color_keys: Some("34"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["clearos"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["clover"],
        colors: &["32", "36"],
        color_keys: Some("32"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["cobalt"],
        colors: &["34", "34", "90", "94", "30"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["codex linux"],
        colors: &["37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["condres"],
        colors: &["32", "33", "36"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["containerlinux", "container linux", "container linux by coreos"],
        colors: &["34", "37", "31"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["common-torizon"],
        colors: &["97", "33", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["cosmic"],
        colors: &["37", "93", "33", "91", "31"],
        color_keys: Some("91"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["crux"],
        colors: &["34", "35", "37"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["crux_small"],
        colors: &["34", "35", "37"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["crystal", "crystal", "crystal-linux", "crystal-linux"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["cucumber", "cucumberos"],
        colors: &["32", "33"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["cuerdos", "cuerdos gnu/linux"],
        colors: &["33", "32"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["cutefishos"],
        colors: &["36", "37", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["cuteos"],
        colors: &["34", "36", "38;5;57"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["cyberos"],
        colors: &["34", "36", "38;5;57"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["cycledream"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["dahliaos"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["darkos"],
        colors: &["31", "36", "35", "33", "32"],
        color_keys: Some("31"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["debian", "debian-linux"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["debian_small", "debian-linux_small"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["deepin", "deepin-linux"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["desaos"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["devuan"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["devuan_small"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["dietpi"],
        colors: &["32", "90"],
        color_keys: Some("90"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["dracos"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["dragonfly"],
        colors: &["31", "39"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["dragonfly_small"],
        colors: &["31", "39"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["dragonfly_old"],
        colors: &["31", "39", "33"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["draugeros", "drauger"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["droidian"],
        colors: &["32", "92"],
        color_keys: Some("32"),
        color_title: Some("92"),
    },
    LogoColorEntry {
        names: &["elbrus"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["elementary"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["elementary_small"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["elive"],
        colors: &["37", "96", "36"],
        color_keys: Some("39"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["emperor"],
        colors: &["33", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["encryptos"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["endeavouros"],
        colors: &["35", "31", "34"],
        color_keys: Some("35"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["endeavouros_small"],
        colors: &["31", "35", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["endless"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["enso"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["eshanizedos"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["eurolinux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["evolutionos"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["evolutionos_small"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["evolutionos_old"],
        colors: &["94", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["eweos"],
        colors: &["37", "93", "91", "90", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["exherbo", "exherbo-linux"],
        colors: &["34", "37", "31"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["exodia predator", "exodia-predator", "exodia predator os"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["fastfetch", "ff"],
        colors: &["34", "31", "33", "32", "39", "35", "36"],
        color_keys: Some("34"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["fedora"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora-asahi-remix"],
        colors: &["33", "32", "31", "90", "37", "36", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["fedora_small"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora2_small"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora_old"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora-silverblue"],
        colors: &["34", "37", "36"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora-kinoite"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora-sericea"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["fedora-coreos"],
        colors: &["34", "37", "31"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["femboyos"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["feren"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["filotimo"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["finnix"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["floflis"],
        colors: &["96"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["freebsd"],
        colors: &["37", "31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["freebsd_small"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["freemint"],
        colors: &["37"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["frugalware", "frugalware-linux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["funtoo"],
        colors: &["35", "37"],
        color_keys: Some("35"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["furreto"],
        colors: &["37", "95"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["galliumos"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["garuda", "garuda-linux"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["garudadragon", "garuda-dragon"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["garuda_small", "garuda-linux_small"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["gentoo"],
        colors: &["35", "37"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["gentoo_small"],
        colors: &["35", "37"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["ghostbsd"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["ghostfreak"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["glaucus"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["gnewsense"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["gnome"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["gnu"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["gobolinux", "gobo"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["goldendog linux", "gdl", "goldendoglinux"],
        colors: &["33"],
        color_keys: Some("35"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["grapheneos"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["grombyang"],
        colors: &["34", "32", "31"],
        color_keys: Some("34"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["guix"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["guix_small"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["gxde"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["haiku"],
        colors: &["39", "32"],
        color_keys: Some("31"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["haiku2"],
        colors: &["32", "39"],
        color_keys: Some("31"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["haiku_small"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["hamonikr"],
        colors: &["34", "37", "38;5;99"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["hardclanz"],
        colors: &["34", "37", "31"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["hardenedbsd"],
        colors: &["37", "31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["harmonyos"],
        colors: &["37", "34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["hash"],
        colors: &["38;5;123", "38;5;123"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["heliumos"],
        colors: &["38;5;81"],
        color_keys: Some("38;5;81"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["huawei cloud euleros", "hce"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["huayra"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["hybrid"],
        colors: &["34", "94"],
        color_keys: Some("94"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["hydroos"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["hypros"],
        colors: &["31", "33", "36", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["hyperbola"],
        colors: &["90"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["hyperbola_small"],
        colors: &["90"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["hydrapwk"],
        colors: &["31", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["iglunix", "iglu"],
        colors: &["90"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["instantos"],
        colors: &["34", "36"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["interix"],
        colors: &["31", "37", "34", "30", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["irix"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ironclad"],
        colors: &["30"],
        color_keys: Some("39"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["itc"],
        colors: &["31"],
        color_keys: Some("39"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["januslinux", "janus"],
        colors: &["34", "35"],
        color_keys: Some("34"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["kaisen"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kali"],
        colors: &["34", "90"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kali_small"],
        colors: &["34", "90"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kalpa-desktop"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kaos"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kernelos"],
        colors: &["31", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["kdelinux", "kde-linux"],
        colors: &["33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["kde neon"],
        colors: &["32", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["kibojoe"],
        colors: &["32", "37", "34"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kiss", "kiss-linux", "kisslinux"],
        colors: &["35", "37", "34"],
        color_keys: Some("35"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["kogaion"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["korora"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["krassos", "krass"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kslinux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["kubuntu", "kubuntu-linux", "kde-ubuntu"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["kylin", "kylin"],
        colors: &["34", "36", "37", "90"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["lainos"],
        colors: &["34", "38;5;14", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["langitketujuh", "l7"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["laxeros"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["lede"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["libreelec"],
        colors: &["32", "33", "37", "36", "35"],
        color_keys: Some("32"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["lilidog"],
        colors: &["34"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["lingmo", "lingmoos"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["linspire", "lindows"],
        colors: &["34", "32"],
        color_keys: Some("34"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["linux", "linux-generic"],
        colors: &["37", "90", "33"],
        color_keys: Some("39"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["linuxfromscratch", "lfs"],
        colors: &["37", "30", "33"],
        color_keys: Some("30"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["linux_small", "linux-generic_small"],
        colors: &["30", "37", "33"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["linuxlite", "linux lite", "linux_lite"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["linuxlite_small", "linux lite_small"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["linuxmint", "linux-mint"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["linuxmint_small", "linux-mint_small"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["linuxmint_old", "linux-mint_old"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["live raizo", "live_raizo"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["lliurex"],
        colors: &["34"],
        color_keys: Some("39"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["lmde"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["locos", "loc-os", "loc-os linux"],
        colors: &["30", "33", "37"],
        color_keys: Some("33"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["lubuntu"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["lunar"],
        colors: &["34", "37", "33"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["macaroni"],
        colors: &["33", "37"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["macos", "mac"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["macos_small", "mac_small"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["macos2", "mac2"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["macos2_small", "mac2_small"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["macos3", "mac3"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["mainsailos"],
        colors: &["31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["mainsailos_small"],
        colors: &["31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["mageia"],
        colors: &["36", "37"],
        color_keys: Some("36"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["mageia_small"],
        colors: &["36", "37"],
        color_keys: Some("36"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["magix", "magixos"],
        colors: &["95", "36"],
        color_keys: Some("36"),
        color_title: Some("95"),
    },
    LogoColorEntry {
        names: &["magpieos", "magpie"],
        colors: &["32", "31", "33", "35"],
        color_keys: Some("32"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["mandriva", "mandrake"],
        colors: &["34", "33"],
        color_keys: Some("34"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["manjaro", "manjaro-arm"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["manjaro_small", "manjaro-arm_small"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["massos", "mass"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["matuusos", "matuus"],
        colors: &["33", "31"],
        color_keys: Some("33"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["maui"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["mauna"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["meowix"],
        colors: &["31", "33", "33", "34"],
        color_keys: Some("31"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["mer"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["midnightbsd"],
        colors: &["39"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["midos"],
        colors: &["90"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["midos_old"],
        colors: &["90", "37"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["minimal_system"],
        colors: &["31"],
        color_keys: Some("36"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["minix"],
        colors: &["31", "37", "33"],
        color_keys: Some("31"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["miracle linux", "miracle_linux"],
        colors: &["38;5;29"],
        color_keys: Some("38;5;29"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["mos"],
        colors: &["36", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["msys2"],
        colors: &["35", "37", "31"],
        color_keys: Some("35"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["mx", "mx linux"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["mx_small", "mx linux_small"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["mx2"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["namib"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nekos"],
        colors: &["33", "37", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["neptune"],
        colors: &["37", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["netrunner"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nexalinux"],
        colors: &["94", "94"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nitrux"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nixos"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nixos_small"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nixos_old"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nixos_old_small"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["netbsd"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["netbsd2"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["netbsd_small"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["nobara", "nobara-linux"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["nomadbsd"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["nuros"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nurunner"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["nutyx"],
        colors: &["34", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["obarun"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["obrevenge"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["obsidianos"],
        colors: &["35", "36", "94"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["omnios"],
        colors: &["37", "33", "90"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["opak"],
        colors: &[],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["openkylin", "open-kylin"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["openbsd"],
        colors: &["33", "37", "36", "31", "90"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["openbsd_small"],
        colors: &["33", "37"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["openeuler"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["openindiana"],
        colors: &["34", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["openmamba"],
        colors: &["37", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["openstage"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["opensuse"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse_small"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-microos"],
        colors: &["32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["opensuse-leap"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-leap_old"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-tumbleweed"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-tumbleweed_small"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-tumbleweed_old"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["opensuse-slowroll", "opensuse-tumbleweed-slowroll"],
        colors: &["39"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["openmandriva", "open-mandriva", "open_mandriva", "openmandriva lx"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["openwrt"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["opnsense"],
        colors: &["37", "38;5;202"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["oracle", "oracle linux", "oracle linux server"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["orchid"],
        colors: &["37", "35", "35"],
        color_keys: Some("39"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["orchid_small"],
        colors: &["37", "35", "35"],
        color_keys: Some("39"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["oreon"],
        colors: &["39", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["os elbrus"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["osmc", "open source media center"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["osx"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["osx_small"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: Some("33"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["pacbsd"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["panwah"],
        colors: &["37", "31", "30"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["parabola", "parabola-gnulinux"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["parabola_small", "parabola-gnulinux_small"],
        colors: &["35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["parch"],
        colors: &["34", "37", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pardus"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["parrot"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["parsix"],
        colors: &["33", "31", "37", "90"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pcbsd", "trueos"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pclinuxos"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pearos"],
        colors: &["32", "33", "31", "35", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pengwin"],
        colors: &["35", "95", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pentoo"],
        colors: &["35", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["peppermint"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["peropesis", "peropesis linux"],
        colors: &["37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["phyos"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pikaos"],
        colors: &["33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pisilinux"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pnm linux"],
        colors: &["34", "31", "37", "38;5;202"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pop", "popos"],
        colors: &["36", "37"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["pop_small", "popos_small"],
        colors: &["36"],
        color_keys: Some("36"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["porteus"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["postmarketos"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["postmarketos_small"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["proxmox", "pve"],
        colors: &["37", "38;5;202"],
        color_keys: Some("39"),
        color_title: Some("38;5;202"),
    },
    LogoColorEntry {
        names: &["puffos"],
        colors: &["33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["puppy"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pureos"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["pureos_small"],
        colors: &["32", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["prismlinux"],
        colors: &["34", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["qts"],
        colors: &["34", "31"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["q4os"],
        colors: &["34", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["qubes"],
        colors: &["34", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["qubyt"],
        colors: &["34", "35", "30"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["quibian"],
        colors: &["33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["quirinux"],
        colors: &["37", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["radix"],
        colors: &["32", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["raspbian", "raspi", "raspberrypi", "raspberrypios"],
        colors: &["31", "32"],
        color_keys: Some("31"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["raspbian_small", "raspi_small", "raspberrypi_small", "raspberrypios_small"],
        colors: &["31", "32"],
        color_keys: Some("31"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["ravynos"],
        colors: &["38;5;15", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["rebornos"],
        colors: &["30", "34", "36"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["rebornos_small"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["redcore"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["rhel", "redhat"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["rhel_small", "redhat_small"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["rhel_old", "redhat_old"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["redos", "red os", "red-os", "redos"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["redos_small", "red os_small", "red-os_small", "redos_small"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["redstar", "redstar-os", "redstaros"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["refracted devuan", "refracted-devuan"],
        colors: &["37", "90"],
        color_keys: Some("90"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["regata"],
        colors: &["37", "31", "34", "35", "33", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["regolith"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["rhaymos"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["rocky", "rocky-linux", "rockylinux"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["rocky_small", "rocky-linux_small", "rockylinux_small"],
        colors: &["32"],
        color_keys: Some("32"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["rosa", "rosa-linux", "rosalinux"],
        colors: &["38;2;250;250;250", "38;2;100;165;225"],
        color_keys: Some("38;2;100;165;225"),
        color_title: Some("38;2;100;165;225"),
    },
    LogoColorEntry {
        names: &["rhino linux"],
        colors: &["35", "94", "95", "35"],
        color_keys: Some("35"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["sabayon"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sabotage"],
        colors: &["39"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["sailfish"],
        colors: &["34", "35"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["salentos"],
        colors: &["32", "31", "33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["salient os", "salientos"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["salix"],
        colors: &["32", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sambabox", "profelis sambabox"],
        colors: &["33", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sasanqua"],
        colors: &["35", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["scientific"],
        colors: &["34", "37", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["secureblue"],
        colors: &["34", "35", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["serpent os"],
        colors: &["39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["semc"],
        colors: &["32", "90", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["septor"],
        colors: &["34", "37", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["serene"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sharklinux"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["shastraos"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["shebang"],
        colors: &["37", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["siduction"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["skiffos"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sleeperos"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["sleeperos_small"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["slitaz"],
        colors: &["33", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["spoinkos", "spoink-os"],
        colors: &["32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["slackel"],
        colors: &["33", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["slackware"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["slackware_small"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["smartos"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["snigdhaos", "snigdha"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["soda"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["source mage", "source mage gnu/linux", "source_mage", "sourcemage"],
        colors: &["39"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["solaris", "sunos"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["solaris_small", "sunos_small"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["solus", "solus-linux"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["sparky"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["star"],
        colors: &["37", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["stock linux"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["steamos"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["steamdeck"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["steamdeck_small"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["steamdeckoled"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["sulin"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["summitos"],
        colors: &["38;2;143;191;80", "38;2;160;205;102", "38;2;181;225;102"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["suse", "suse-linux"],
        colors: &["32", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["suse_small", "suse-linux_small"],
        colors: &["32", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["swagarch"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["t2", "t2 sde", "t2/linux"],
        colors: &["31", "37", "33", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["t2_small", "t2 sde_small", "t2/linux_small"],
        colors: &["37", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["tails"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["tatra"],
        colors: &["34", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["tearch"],
        colors: &["38;5;39", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["templeos"],
        colors: &["33", "31", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["tileos"],
        colors: &["35", "34", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["torizon os", "torizoncore"],
        colors: &["97", "33", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["trisquel"],
        colors: &["34", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["truenas-scale"],
        colors: &["38;5;39", "38;5;32", "38;5;248"],
        color_keys: Some("38;5;248"),
        color_title: Some("38;5;32"),
    },
    LogoColorEntry {
        names: &["tuxedo os", "tuxedo"],
        colors: &["37", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["twister"],
        colors: &["32", "31", "34", "35", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ublinux"],
        colors: &["38;5;38", "37", "90"],
        color_keys: Some("38;5;38"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ublinux_small"],
        colors: &["38;5;38", "37", "90"],
        color_keys: Some("38;5;38"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ubuntu", "ubuntu-linux"],
        colors: &["31", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu_small", "ubuntu-linux_small"],
        colors: &["31", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu_old", "ubuntu-linux_old"],
        colors: &["31", "37"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["ubuntu_old2"],
        colors: &["31", "37", "33"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["ubuntu_old2_small", "ubuntu_old2_small"],
        colors: &["31"],
        color_keys: Some("31"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["ubuntu budgie", "ubuntu-budgie"],
        colors: &["34", "37", "31"],
        color_keys: Some("34"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ubuntu cinnamon", "ubuntu-cinnamon"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu gnome", "ubuntu-gnome"],
        colors: &["34", "35", "37", "36"],
        color_keys: Some("34"),
        color_title: Some("35"),
    },
    LogoColorEntry {
        names: &["ubuntu kylin", "ubuntu-kylin"],
        colors: &["31", "37", "33"],
        color_keys: Some("31"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ubuntu mate", "ubuntu-mate"],
        colors: &["32", "37"],
        color_keys: Some("32"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["ubuntu kde", "ubuntu-kde", "ubuntu-plasma"],
        colors: &["34", "37"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["ubuntu studio", "ubuntu-studio"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu sway", "ubuntu-sway"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu touch", "ubuntu-touch"],
        colors: &["33", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ubuntu unity", "ubuntu-unity"],
        colors: &["35", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ultramarine", "ultramarine linux"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["ultramarine_small"],
        colors: &["34", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["unifi"],
        colors: &["37", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["univalent"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["univention"],
        colors: &["31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["uos"],
        colors: &["31"],
        color_keys: Some("39"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["urukos"],
        colors: &["94", "94", "37", "94", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["uwuntu"],
        colors: &["38;5;225", "38;5;206", "38;5;52"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["valhalla", "valhallaos", "valhalla-linux"],
        colors: &["39"],
        color_keys: Some("39"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["vanilla"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["vanilla2"],
        colors: &["33"],
        color_keys: Some("33"),
        color_title: Some("33"),
    },
    LogoColorEntry {
        names: &["vanilla_small"],
        colors: &["93", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["venom"],
        colors: &["90", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["venom_small"],
        colors: &["90", "34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["vnux"],
        colors: &["38;5;11", "38;5;8", "38;5;15", "31", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["vzlinux"],
        colors: &["31", "37", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["void"],
        colors: &["32", "90"],
        color_keys: Some("39"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["void_small"],
        colors: &["32"],
        color_keys: Some("39"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["void2"],
        colors: &["33", "39", "32"],
        color_keys: Some("39"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["void2_small"],
        colors: &["32"],
        color_keys: Some("39"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["wiilinuxngx", "wiilinux", "wii-linux", "wii linux"],
        colors: &["36", "37"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["windows server 2025"],
        colors: &["34", "34", "34", "34"],
        color_keys: Some("33"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["windows 11", "windows server 2022"],
        colors: &["34", "34", "34", "34"],
        color_keys: Some("33"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["windows 11_small"],
        colors: &["34", "34", "34", "34"],
        color_keys: Some("33"),
        color_title: Some("36"),
    },
    LogoColorEntry {
        names: &["windows 8", "windows 8.1", "windows 10", "windows server 2012", "windows server 2012 r2", "windows server 2016", "windows server 2019"],
        colors: &["36", "36", "36", "36"],
        color_keys: Some("33"),
        color_title: Some("39"),
    },
    LogoColorEntry {
        names: &["windows", "windows 7", "windows server 2008", "windows server 2008 r2"],
        colors: &["31", "32", "34", "33"],
        color_keys: Some("34"),
        color_title: Some("32"),
    },
    LogoColorEntry {
        names: &["windows 95", "windows 9x"],
        colors: &["36", "34", "33", "32", "31", "30"],
        color_keys: Some("36"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["wolfos"],
        colors: &["34", "32"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xcp-ng", "xenenterprise"],
        colors: &["31", "31", "30", "30", "34", "33"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xenia"],
        colors: &["31", "90"],
        color_keys: Some("39"),
        color_title: Some("31"),
    },
    LogoColorEntry {
        names: &["xenia_old"],
        colors: &["33", "32", "31"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xeroarch"],
        colors: &["38;5;50", "38;5;14", "38;5;50", "38;5;93", "38;5;16", "38;5;15"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xferience"],
        colors: &["36", "36"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xubuntu"],
        colors: &["38;5;25", "39"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["xray_os"],
        colors: &["38;5;15", "38;5;14", "38;5;16"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["yiffos"],
        colors: &["38;5;93", "38;5;92"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["zorin"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
    LogoColorEntry {
        names: &["z/os", "zos"],
        colors: &["34"],
        color_keys: None,
        color_title: None,
    },
    LogoColorEntry {
        names: &["zraxyl"],
        colors: &["34"],
        color_keys: Some("34"),
        color_title: Some("34"),
    },
];